# Generated by Django 5.0.6 on 2026-04-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='competencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
